version: '3.8'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8080}
